### ISSUE TITLE
Be able to react to palette UI state

### ISSUE THREAD

**Issue by nikku** [bpmn-io/diagram-js#591]
__Is your feature request related to a problem? Please describe.__

Right now I have no way to safely hook into the palette collapsed / expanded state (CSS wise). As a result an integration must listen to palette events and react accordingly.

__Describe the solution you'd like__

I'd love to have a way for components to hook into palette collapsed / expanded state via CSS only, i.e.:

```css
.djs-palette-open .my-label {
  top: 200px;
}

.djs-palette-closed .my-label {
  top: 100px;
}

.djs-palette-two-column .my-other-label {
  ...
}
```

Related but different: Expose core layout metrics (palette width, height, spacing) as CSS variables so components can safely re-use them for layouting:

```css
.djs-palette-open {
   top: var(--palette-open-bottom);
}
```

__Describe alternatives you've considered__

Accept that we have to use complicated integrations (hook into palette events) to react to palette state. Verify that all state transitions can be hooked into.

__Additional context__

We do have a similar issue with the newly implemented [drilldown overlays](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/drilldown/DrilldownOverlays.js) in bpmn-js. Whatever solution we adopt here, we shall adopt it there, too.
